services:
  db:
    image: postgres:14.2-alpine
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres", "-c", "SELECT 1;" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    ports:
      - 5432:5432
     
  rabbits:
    image: rabbitmq:3-management-alpine
    container_name: rabbits
    environment:
      - "RABBITMQ_DEFAULT_PASS=RABBITMQ_DEFAULT_PASS"
      - "RABBITMQ_DEFAULT_USER=RABBITMQ_DEFAULT_USER"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
