version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=DEFAULT_USER
      - POSTGRES_PASSWORD=DEFAULT_PASS
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:

  rabbits:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbits'
    environment:
      - "RABBITMQ_DEFAULT_PASS=RABBITMQ_DEFAULT_PASS"
      - "RABBITMQ_DEFAULT_USER=RABBITMQ_DEFAULT_USER"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

