version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432

  rabbits:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbits'
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
